# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=20)),
                ('video_director', models.CharField(max_length=40)),
                ('video_actor', models.CharField(max_length=40)),
                ('video_language', models.CharField(max_length=15)),
                ('video_district', models.CharField(max_length=15)),
                ('video_tag', models.CharField(max_length=50)),
                ('video_type', models.CharField(max_length=20)),
                ('video_path', models.CharField(max_length=60)),
                ('video_pic_path', models.CharField(max_length=60)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
