# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('product_show_time', models.IntegerField()),
                ('product_pic_path', models.CharField(max_length=200)),
                ('product_buy_url', models.CharField(max_length=200)),
                ('product_key_en', models.CharField(max_length=50)),
                ('product_key_ch', models.CharField(max_length=50)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='trailer.Video')),
            ],
        ),
    ]
