# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_thumnail_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
