# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0003_video_video_thumnail_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_thumnail_path',
            new_name='video_thumbnail_path',
        ),
    ]
